sequenceDiagram
    participant Client
    participant Microsoft Entra ID (/oauth2/v2.0/token)

    Client->>Microsoft Entra ID (/oauth2/v2.0/token): トークンリクエスト（client_id + client_secret + scope）
    Microsoft Entra ID (/oauth2/v2.0/token)->>Client: アクセストークン
